### ISSUE TITLE
Demo doesn't work on Django1.7

### ISSUE THREAD

**Issue by sebastianjaszczur** [gkmngrgn/django-voice#59]
Steps to reproduce:
Run 'python manage.py runserver' for demo.

Output:
```
/usr/local/lib/python2.7/dist-packages/django/contrib/comments/__init__.py:13: RemovedInDjango18Warning: django.contrib.comments is deprecated and will be removed before Django 1.8.
  warnings.warn("django.contrib.comments is deprecated and will be removed before Django 1.8.", RemovedInDjango18Warning)

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/qhonuskan_votes/models.py", line 6, in <module>
    from qhonuskan_votes.compat import User
  File "/usr/local/lib/python2.7/dist-packages/qhonuskan_votes/compat.py", line 8, in <module>
    User = get_user_model()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 137, in get_user_model
    return django_apps.get_model(settings.AUTH_USER_MODEL)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 199, in get_model
    self.check_models_ready()
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 131, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
```

**Comment by kevinmickey** [comment]
This is an issue with the qhonuskan-votes package.  See linkfloyd/qhonuskan-votes#14.  In the meantime, if you need it to work, try changing the line in [requirements/global.txt](../blob/master/requirements/global.txt) from git+git://github.com/linkfloyd/qhonuskan-votes.git@master to git+git://github.com/laginha/qhonuskan-votes.git@master

**Comment by kevinmickey** [comment]
But it looks like the same issue affects [djangovoice/models.py](../blob/master/djangovoice/models.py). See https://docs.djangoproject.com/en/1.8/topics/auth/customizing/#referencing-the-user-model
