### ISSUE TITLE
Demo doesn't work on Django 1.8

### ISSUE THREAD

**Issue by kevinmickey** [gkmngrgn/django-voice#60]
I was able to get this to run on Django 1.7 (see #59), but I'm having trouble with 1.8.  I can run the server and access the demo homepage, but I get this error when I try to go to the feedback page:
```
Internal Server Error: /feedback/
Traceback (most recent call last):
  File "/Users/kevin/.envs/django-voice/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/kevin/.envs/django-voice/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/kevin/.envs/django-voice/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/kevin/Downloads/django-voice/demo/djangovoice/views.py", line 125, in get
    return super(FeedbackListView, self).get(request, *args, **kwargs)
  File "/Users/kevin/.envs/django-voice/lib/python2.7/site-packages/django/views/generic/list.py", line 174, in get
    context = self.get_context_data()
  File "/Users/kevin/Downloads/django-voice/demo/djangovoice/views.py", line 104, in get_context_data
    data = super(FeedbackListView, self).get_context_data(**kwargs)
  File "/Users/kevin/Downloads/django-voice/demo/djangovoice/mixins.py", line 6, in get_context_data
    context = super(VoiceMixin, self).get_context_data(**kwargs)
  File "/Users/kevin/.envs/django-voice/lib/python2.7/site-packages/django/views/generic/list.py", line 134, in get_context_data
    paginator, page, queryset, is_paginated = self.paginate_queryset(queryset, page_size)
  File "/Users/kevin/.envs/django-voice/lib/python2.7/site-packages/django/views/generic/list.py", line 78, in paginate_queryset
    page = paginator.page(page_number)
  File "/Users/kevin/.envs/django-voice/lib/python2.7/site-packages/django/core/paginator.py", line 50, in page
    number = self.validate_number(number)
  File "/Users/kevin/.envs/django-voice/lib/python2.7/site-packages/django/core/paginator.py", line 39, in validate_number
    if number > self.num_pages:
  File "/Users/kevin/.envs/django-voice/lib/python2.7/site-packages/django/core/paginator.py", line 86, in _get_num_pages
    if self.count == 0 and not self.allow_empty_first_page:
  File "/Users/kevin/.envs/django-voice/lib/python2.7/site-packages/django/core/paginator.py", line 72, in _get_count
    self._count = self.object_list.count()
  File "/Users/kevin/.envs/django-voice/lib/python2.7/site-packages/django/db/models/query.py", line 318, in count
    return self.query.get_count(using=self.db)
  File "/Users/kevin/.envs/django-voice/lib/python2.7/site-packages/django/db/models/sql/query.py", line 466, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/Users/kevin/.envs/django-voice/lib/python2.7/site-packages/django/db/models/sql/query.py", line 447, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/Users/kevin/.envs/django-voice/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/Users/kevin/.envs/django-voice/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/kevin/.envs/django-voice/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/kevin/.envs/django-voice/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/kevin/.envs/django-voice/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/kevin/.envs/django-voice/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such function: None
```

**Comment by kevinmickey** [comment]
Looks like this is an issue with linkfloyd/qhonuskan-votes - see linkfloyd/qhonuskan-votes#24
